In [ ]:
!pip install wget

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: wget in /usr/local/lib/python3.8/dist-packages (3.2)

In [ ]:
import os
import pandas as pd
import wget

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ADL_Images/BX_Books.csv', encoding= 'ISO-8859-1', error_bad_lines=False, sep=';')
df.head()

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton & Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...

In [ ]:
df.shape

(271379, 8)

In [ ]:
df1 = pd.read_csv('/content/drive/MyDrive/ADL_Images/BX-Book-Ratings.csv', encoding= 'ISO-8859-1', error_bad_lines=False, sep=';')
df1.head()

/usr/local/lib/python3.8/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6

In [ ]:
df1.shape

(1149780, 3)

In [ ]:
df1['ISBN'].value_counts()
df1 = df1.groupby('ISBN', as_index=False)['Book-Rating'].mean()

In [ ]:
df1.shape

(340556, 2)

In [ ]:
df_final = df.merge(df1,on='ISBN',how='left')

In [ ]:
df_final

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L,Book-Rating
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,0.000000
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,4.928571
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,5.000000
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,4.272727
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton & Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,0.000000
...,...,...,...,...,...,...,...,...,...
271374,0440400988,There's a Bat in Bunk Five,Paula Danziger,1988,Random House Childrens Pub (Mm),http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,http://images.amazon.com/images/P/0440400988.0...,7.000000
271375,0525447644,From One to One Hundred,Teri Sloat,1991,Dutton Books,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,http://images.amazon.com/images/P/0525447644.0...,4.000000
271376,006008667X,Lily Dale : The True Story of the Town that Ta...,Christine Wicker,2004,HarperSanFrancisco,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,http://images.amazon.com/images/P/006008667X.0...,0.000000
271377,0192126040,Republic (World's Classics),Plato,1996,Oxford University Press,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,http://images.amazon.com/images/P/0192126040.0...,0.000000
271378,0767409752,A Guided Tour of Rene Descartes' Meditations o...,Christopher Biffle,2000,McGraw-Hill Humanities/Social Sciences/Languages,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,http://images.amazon.com/images/P/0767409752.0...,0.000000

In [ ]:
df_final = df_final[['ISBN', 'Image-URL-L', 'Book-Rating']]
# df_final.to_csv('/content/drive/MyDrive/ADL_Images/final_data.csv', index = False)
# df_final['Image-URL-L'].to_csv('/content/drive/MyDrive/ADL_Images/url_list.csv', index= False)
df_final.dropna(inplace = True)
df_final.isna().sum()

/usr/local/lib/python3.8/dist-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

ISBN           0
Image-URL-L    0
Book-Rating    0
dtype: int64

##Download Images

In [ ]:
df_final['Image-URL-L'][0]

'http://images.amazon.com/images/P/0195153448.01.LZZZZZZZ.jpg'

In [ ]:
from urllib.request import Request, urlopen

# Function to get the page content
def get_page_content(url, head):
  """
  Function to get the page content
  """
  req = Request(url, headers=head)
  return urlopen(req)



head = {
  'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36',
  'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9',
  'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3',
  'Accept-Encoding': 'none',
  'Accept-Language': 'en-US,en;q=0.8',
  'Connection': 'keep-alive',
  'refere': 'https://example.com',
  'cookie': """your cookie value ( you can get that from your web page) """
}


for url in df_final['Image-URL-L']:
  data = get_page_content(url, head).read()

  save_as = url.split('/')[-1].split('.')[0]
  print(save_as)

  with open('/content/drive/MyDrive/ADL_Images/all_images/'+save_as+'.jpg', 'wb') as handler:
    handler.write(data)

0195153448
0002005018
0060973129
0374157065
0393045218
0399135782
0425176428
0671870432
0679425608
074322678X
0771074670
080652121X
0887841740
1552041778
1558746218
1567407781
1575663937
1881320189
0440234743
0452264464
0609804618
1841721522
1879384493
0061076031
0439095026
0689821166
0971880107
0345402871
0345417623
0684823802
0375759778
0425163091
3404921038
3442353866
3442410665
3442446937
0375406328
0446310786
0449005615
0060168013
038078243X
055321215X
067176537X
0061099686
0553582909
0671888587
0553582747
0425182908
042518630X
0440223571
0812523873
0842342702
0440225701
0060914068
0156047624
0245542957
0380715899
0553280333
0961769947
0964778319
0671623249
0679810307
0679865691
2070423204
0345260317
0394743741
042511774X
0804106304
1853262404
0312970242
1853260053
1414035004
0060938412
0140067477
0345465083
0451625889
1558531025
0441783589
0394895894
1569871213
0375410538
0966986105
087113375X
0340767936
0743403843
0060930365
0060177586
0071416331
0375509038
0553062042
0316769487
8445071408
8445071769
8445071777
0679429220
0671867156
0312252617
0312261594
0316748641
0316973742
0385235941
0446677450
0451166892
0553347594
0671621009
067976397X
0684822733
0786868716
8472238822
0671864769
0671521519
0440222303
0312953453
0446608653
0446612545
0446612618
0451208080
0553584383
0671027360
0812575954
0316735736
0743439740
0345372700
0380619458
0446325805
0451406923
0671042858
0743249992
0840734530
0425184226
0375500766
9724119378
0451205197
0060929790
0060976845
0061099325
0671004573
0446601640
0330484516
038572179X
0393020371
1900850303
1903019699
0345425294
0451410319
0553583468
8420639133
8476409419
0380778556
0451525221
0002740230
0385336772
0440949424
0505524996
0140252800
0451452755
0812575482
044651747X
0060801263
0061030147
0140250964
0446527165
0671461494
0385337639
039575514X
0451206673
0330332775
0486284735
0671021745
0671047612
0671504282
0399138684
0785263292
0830714014
0345354931
0553278223
3150000335
3257203659
3257207522
3257208626
3257208634
3257208669
3257210450
3257212054
3257212429
3257214154
3257216416
3257233051
342311360X
3423116714
3423241489
3426605686
3453212150
3462021095
3492045642
3498020862
3499110695
3499151502
3518111000
3548254268
3570300099
3596292646
0060977493
0312872682
0316602906
0316693006
0345311396
0345378490
0345404793
0345433173
0375400117
0375705856
0380717018
0380718332
0380754509
038076654X
0380807866
0385316895
0385497466
0385508042
0385509456
0385511612
0385730586
0425164403
0440234964
0446605484
0446610399
0449006522
0449911004
0451162072
0451186648
0452282152
051513290X
0553580388
0590598848
0590629719
0671023616
0671027387
0684848783
0743486226
0786863986
0803251718
0804117934
140003180X
155874262X
0060987103
0151008116
0375704965
0525947647
0804111359
1558744150
0435272683
0316782505
006102063X
0060013117
0060199563
006052779X
0060563079
0060809027
0061040967
0061050474
0061052515
0061052523
0064472264
0140620664
0312148267
0312156960
0312890044
034543191X
0373836023
0375751513
0375801677
0375814248
0375823352
037582345X
0375823468
0380730448
0380973839
0385327773
0394586239
0439510112
0440241413
0451409256
0451523415
0451526279
0451526341
0486415864
0553280589
0571197639
0670035262
0679423079
0679751343
0684833395
0743245024
0749748001
0749748028
0963094424
1401201172
1563892278
1563898586
156971620X
1592571301
0374270325
0375719180
0440235502
044023722X
1573225487
1853260673
0060977477
0345391691
0520011171
0553278746
0670856045
0872200760
0937858994
0671649949
0590431110
0064470113
0553571486
0972044205
0312963009
0345430476
0345435869
0380728729
038081840X
0449912302
055329198X
0671018930
0812541642
0312988699
0486282112
8483007010
0670815373
0385313748
1575843366
0684193957
0345371984
0380730138
1573228737
9681500555
0380711109
0452283914
0425120279
067153484X
0380728273
8433914545
8484509141
0446606197
0771076002
0771088191
1559703237
3596214629
0062770500
0671847546
0060188731
0140374248
0142001740
0195086295
0312995423
0380704587
0380815923
0385416342
0385418493
038542471X
0425098109
0449005410
0449202631
0449207544
0515128554
0517577402
0590450875
0590481371
067103619X
0684177730
0684180200
0743411269
0743470389
076218857X
0767905938
0800706544
0801096677
0849953014
0891091963
0915811537
0927545373
1575024179
1880185008
0140345809
0156528207
0380012863
0451154916
0785815147
0875421288
1567184294
156718796X
1862047626
0020437501
0198320264
0373196989
0373245580
0451527747
0671867113
0812504208
0060173289
0060973897
006101351X
0140104682
0312143370
0316666343
039456894X
0440224675
0449002632
0449213773
0452279690
0553569058
0679427430
0679725393
0802114369
0803233019
0819154946
0897322339
0940322978
1573225126
1579651658
1878424319
8401351421
8423324311
8427007450
8429734996
8429736131
8440616252
8472224260
8472227421
8474103347
8475960936
8477830029
8478091246
8478097732
8478098267
8478800336
8478884963
8483002523
8486433193
0600586898
1853260622
1857938011
0060804157
8466601090
0140382658
0152012966
0312283784
0345297709
0345313097
0345335465
0345416848
0385333404
044021145X
0449212084
0553582682
0590947257
074345829X
0786913878
0801491827
0816729913
0843136685
0866119531
0866119566
0870441663
1561561428
0553210092
0553258524
0688163726
1569471096
055358099X
0316168815
014023828X
0316314927
0345424719
0375414746
0375726403
0385503857
0425156842
0440226104
0452277337
0553802488
0671021001
0767903579
0805063897
0679777431
0553285343
0486285529
0671002481
0812523385
0895774666
0020199090
0385495145
0679733825
0842329129
0345451260
0740700235
0380973545
0393321576
0743424425
0786868015
0446610178
0684854953
0743229878
0380617625
0380732335
0385337132
0440235057
0445402040
0618119760
0871138646
0026329859
0060621257
0060915544
0060917016
0060925000
0060932759
0061000280
0192815318
0312195516
0380792664
0393048977
0399137807
039914739X
0451203046
0451410556
0451523318
0486281965
0486292940
051762639X
0684824442
0743458303
081296666X
0819215635
0880011025
1561011525
1877727083
0486206173
0312278586
8845229041
887641486X
0140370900
0674511255
0030096189
0312965745
0345374657
0395710901
080521061X
0823032612
0679310002
0312288115
0316171107
0380710218
0515118656
0553289063
0671000306
0671673688
1561672033
0425178242
0618173870
0156027321
0375403582
0385721420
0451202341
0743418190
0385335407
0965746828